sudo: required
services:
  - docker

before_install:
  - docker build -t kshitijsharma23/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kshitijsharma23/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  # Region where Elastic Beanstalk instance is deployed.
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  # S3 bucket where code is deployed.
  bucket_name: "elasticbeanstalk-us-east-2-828699529795"
  # Bucket path is same as app name.
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
