sudo: required
services:
  - docker

before_install:
  - docker build -t kshitijsharma23/docker-react -f Dockerfile.dev .

script:
  - docker run kshitijsharma23/docker-react npm run test -- --coverage